import {
  contentSchema,
  normalizeContent,
  type Content,
  type Kind,
  type RecordItem,
} from "./schema";

const data = (v: Partial<Content>, kind: Kind = "page", slug = "") =>
  normalizeContent(contentSchema.parse(v), kind, slug);

const BRAND_1_ID = "00000000-0000-4000-8000-000000000020";
const COLLECTION_1_ID = "00000000-0000-4000-8000-000000000030";
const PROD_1_ID = "00000000-0000-4000-8000-000000000041";
const PROD_2_ID = "00000000-0000-4000-8000-000000000042";
const PROD_3_ID = "00000000-0000-4000-8000-000000000043";

const record = (
  id: string,
  kind: Kind,
  slug: string,
  c: Partial<Content>,
): RecordItem => {
  const parsed = data(c, kind, slug);
  return {
    id,
    kind,
    slug,
    draft: parsed,
    published: parsed,
    updated_at: "2026-09-22T00:00:00.000Z",
    published_at: "2026-09-22T00:00:00.000Z",
  };
};

export const seed: RecordItem[] = [
  record("00000000-0000-4000-8000-000000000001", "settings", "company", {
    title: "Mack Knit Wear",
    summary: "A considered approach to knitwear, fine textiles, and brand partnerships.",
    footer: "Knitwear. Brands. Connections.",
    footerNote: "A world of possibilities, woven together.",
    logoTagline: "KNITWEAR & BEYOND",
    body: "Mack Knit Wear is a specialized knitwear manufacturing and brand development group based in Dhaka, Bangladesh, producing premium knit apparel for global markets.",
    email: "inquiries@mackknitwear.com",
    phone: "+880 2 887 8100",
    address: "Tejgaon Industrial Area, Dhaka 1208, Bangladesh",
    linkedin: "https://linkedin.com/company/mack-knit-wear",
    facebook: "https://facebook.com/mackknitwear",
    responsePromise: "We review business inquiries within two business days.",
    enableSampleRequests: true,
    locations: [
      {
        id: "loc-dhaka-hq",
        name: "Dhaka Headquarters & Showroom",
        address: "Plot 42, Tejgaon Commercial Area, Dhaka 1208, Bangladesh",
        phone: "+880 2 887 8100",
        email: "dhaka@mackknitwear.com",
        hours: "Mon – Fri: 09:00 – 18:00 BST",
        directionsUrl: "https://maps.google.com/?q=Tejgaon+Dhaka",
        isHeadquarters: true,
      },
      {
        id: "loc-gazipur-facility",
        name: "Gazipur Knitting Facility & Lab",
        address: "Kashimpur Road, Gazipur 1700, Bangladesh",
        phone: "+880 2 926 4500",
        email: "operations@mackknitwear.com",
        hours: "Mon – Sat: 08:00 – 17:00 BST",
        directionsUrl: "https://maps.google.com/?q=Gazipur+Bangladesh",
        isHeadquarters: false,
      },
      {
        id: "loc-london-liaison",
        name: "European Liaison Office",
        address: "71-75 Shelton Street, Covent Garden, London WC2H 9JQ, United Kingdom",
        phone: "+44 20 7946 0912",
        email: "europe@mackknitwear.com",
        hours: "Mon – Fri: 09:00 – 17:00 GMT",
        directionsUrl: "https://maps.google.com/?q=Shelton+Street+London",
        isHeadquarters: false,
      },
    ],
    headerNav: [
      { id: "nav-about", label: "About us", href: "/about", isExternal: false, visible: true, order: 1 },
      { id: "nav-brands", label: "Our brands", href: "/brands", isExternal: false, visible: true, order: 2 },
      { id: "nav-products", label: "Products", href: "/products", isExternal: false, visible: true, order: 3 },
      { id: "nav-capabilities", label: "Capabilities", href: "/capabilities", isExternal: false, visible: true, order: 4 },
      { id: "nav-network", label: "Our network", href: "/network", isExternal: false, visible: true, order: 5 },
    ],
    footerNav: [
      { id: "fnav-about", label: "About us", href: "/about", isExternal: false, visible: true, order: 1 },
      { id: "fnav-brands", label: "Our brands", href: "/brands", isExternal: false, visible: true, order: 2 },
      { id: "fnav-products", label: "Catalogue", href: "/products", isExternal: false, visible: true, order: 3 },
      { id: "fnav-contact", label: "Contact & Inquiries", href: "/contact", isExternal: false, visible: true, order: 4 },
      { id: "fnav-privacy", label: "Privacy policy", href: "/privacy", isExternal: false, visible: true, order: 5 },
    ],
  }),

  // Core Pages
  record("00000000-0000-4000-8000-000000000010", "page", "home", {
    template: "company",
    title: "Made of possibility.",
    eyebrow: "MACK KNIT WEAR",
    summary: "A home for knitwear craftsmanship, emerging brands, and meaningful international manufacturing partnerships.",
    body: "Explore the enterprise behind the collection. Discover our owned brands, inspect verified technical capabilities, and start a conversation on wholesale or private-label production.",
    image: "/images/knitwear.jpg",
    imageAlt: "Close-up textile photograph used as illustrative design imagery",
    ctaLabel: "Discover our brands",
    ctaHref: "/brands",
    sections: [
      {
        id: "sec-home-hero",
        type: "editorial_hero",
        enabled: true,
        order: 1,
        title: "Made of possibility.",
        eyebrow: "MACK KNIT WEAR",
        content: "A home for knitwear craftsmanship, emerging brands, and meaningful international manufacturing partnerships.",
        image: "/images/knitwear.jpg",
        imageAlt: "Close-up textile photograph used as illustrative design imagery",
        ctaLabel: "Discover our brands",
        ctaHref: "/brands",
        data: {},
      },
      {
        id: "sec-home-brands",
        type: "brand_showcase",
        enabled: true,
        order: 2,
        title: "A character of its own.",
        eyebrow: "02 — OUR BRAND PORTFOLIO",
        content: "Each owned brand has an autonomous voice, distinct material philosophy, and dedicated collection focus.",
        image: "",
        imageAlt: "",
        ctaLabel: "Explore all brands",
        ctaHref: "/brands",
        data: { limit: 4 },
      },
      {
        id: "sec-home-products",
        type: "product_showcase",
        enabled: true,
        order: 3,
        title: "Featured Knitwear",
        eyebrow: "03 — CRAFTSMANSHIP IN DETAIL",
        content: "Precision knitted garments manufactured using fine wools, combed cottons, and blended yarns.",
        image: "",
        imageAlt: "",
        ctaLabel: "Browse product catalogue",
        ctaHref: "/products",
        data: { itemIds: [PROD_1_ID, PROD_2_ID, PROD_3_ID] },
      },
      {
        id: "sec-home-facts",
        type: "company_facts",
        enabled: true,
        order: 4,
        title: "Verified Enterprise Milestones",
        eyebrow: "04 — SCALE & INTEGRITY",
        content: "Every metric represents audited manufacturing capacity and trade compliance.",
        image: "",
        imageAlt: "",
        ctaLabel: "",
        ctaHref: "",
        data: {
          facts: [
            { value: "48+", label: "Gauge capabilities", note: "3G to 16G flat & circular knitting" },
            { value: "1.2M", label: "Annual capacity", note: "Pieces across sweater & jersey divisions" },
            { value: "100%", label: "Traceable yarns", note: "GOTS & OEKO-TEX Standard 100 certified" },
            { value: "14", label: "Export markets", note: "Europe, North America & Asia-Pacific" },
          ],
        },
      },
      {
        id: "sec-home-contact",
        type: "contact_banner",
        enabled: true,
        order: 5,
        title: "Let’s make a connection.",
        eyebrow: "THE NEXT CHAPTER STARTS WITH A CONVERSATION",
        content: "Whether you are interested in wholesale orders, partnership, or visiting our Dhaka facility.",
        image: "",
        imageAlt: "",
        ctaLabel: "Get in touch",
        ctaHref: "/contact",
        data: {},
      },
    ],
  }),

  record("00000000-0000-4000-8000-000000000011", "page", "about", {
    template: "company",
    title: "The company behind the possibilities.",
    eyebrow: "ABOUT MACK",
    summary: "From heritage textile foundations to a forward-looking knitwear design and manufacturing group.",
    body: "Founded with an obsession for tactile quality and technical knitting precision, Mack Knit Wear combines traditional finishing craftsmanship with modern computerized knitting machinery. Based in Dhaka, Bangladesh, we work with global fashion labels, independent designers, and our own portfolio of emerging brands.",
    image: "/images/knitwear.jpg",
    imageAlt: "Intricate knitted textile detail showing stitch definition",
    sections: [
      {
        id: "sec-about-story",
        type: "image_text",
        enabled: true,
        order: 1,
        title: "Crafting knitwear with conscience and precision.",
        eyebrow: "OUR PHILOSOPHY",
        content: "We believe exceptional knitwear is born at the intersection of fiber selection, gauge mastery, and mindful working conditions. We operate a modern vertical production facility in Gazipur, Bangladesh, upholding strict labor standards, energy efficiency, and low-waste production methodologies.",
        image: "/images/knitwear.jpg",
        imageAlt: "Textile machinery and finished knit swatches",
        ctaLabel: "Inspect capabilities",
        ctaHref: "/capabilities",
        data: {},
      },
      {
        id: "sec-about-timeline",
        type: "timeline",
        enabled: true,
        order: 2,
        title: "Our Journey",
        eyebrow: "HISTORICAL MILESTONES",
        content: "Key moments in our evolution as an international knitwear manufacturer.",
        image: "",
        imageAlt: "",
        ctaLabel: "",
        ctaHref: "",
        data: {
          milestones: [
            { year: "2016", title: "Foundations Established", description: "Inaugural flat-knitting workshop established in Dhaka with 20 manual hand-flat machines." },
            { year: "2019", title: "Modern Automation", description: "Commissioned computerized Shima Seiki multi-gauge knitting systems and expanded into fine wool processing." },
            { year: "2022", title: "Brand Portfolio Launch", description: "Launched our first proprietary consumer-facing knitwear label and expanded into European wholesale." },
            { year: "2025", title: "Zero-Waste Lab", description: "Achieved full-fashioned zero-waste knitting certification across our core fine merino line." },
          ],
        },
      },
    ],
  }),

  record("00000000-0000-4000-8000-000000000012", "page", "brands", {
    template: "brand_directory",
    title: "Individual identities. Shared ambition.",
    eyebrow: "OUR BRANDS",
    summary: "Discover the consumer and wholesale brands developed under the Mack Knit Wear umbrella.",
    body: "Each brand within our portfolio possesses its own creative direction, material standards, and target lifestyle, backed by the industrial manufacturing excellence of Mack Knit Wear.",
  }),

  record("00000000-0000-4000-8000-000000000013", "page", "products", {
    template: "product_directory",
    title: "Explore what we do.",
    eyebrow: "PRODUCTS & CATALOGUE",
    summary: "Discover our confirmed knitwear product specifications, materials, and technical capabilities.",
    body: "Filter through fine gauge sweaters, heavy gauge cardigans, and seasonal collections developed for wholesale distribution and private label manufacturing.",
  }),

  record("00000000-0000-4000-8000-000000000014", "page", "capabilities", {
    template: "capabilities",
    title: "Manufacturing Craftsmanship & Facilities.",
    eyebrow: "OUR CAPABILITIES",
    summary: "Technical knitting mastery across fine and chunky gauges, eco-friendly washing, and bespoke garment engineering.",
    body: "Our facilities in Gazipur and Dhaka combine state-of-the-art Japanese knitting technology with artisanal link-and-seam finishing to deliver garments of world-class durability and hand-feel.",
  }),

  record("00000000-0000-4000-8000-000000000015", "page", "network", {
    template: "network",
    title: "Connected through opportunity.",
    eyebrow: "OUR NETWORK",
    summary: "The strategic relationships, represented brands, retail partners, and sister enterprises connecting our work.",
    body: "We partner with visionary fashion labels, international yarn mills, and established retailers across four continents.",
  }),

  record("00000000-0000-4000-8000-000000000016", "page", "contact", {
    template: "contact",
    title: "Let’s start a conversation.",
    eyebrow: "CONTACT",
    summary: "Reach out to discuss wholesale opportunities, private label development, brand partnerships, or factory visits.",
    body: "Our team in Dhaka and London is ready to assist you. Choose your inquiry type below to route your request directly to the appropriate specialist.",
  }),

  record("00000000-0000-4000-8000-000000000017", "page", "privacy", {
    template: "policy",
    title: "Privacy Notice & Data Policy",
    eyebrow: "LEGAL & COMPLIANCE",
    summary: "How Mack Knit Wear collects, handles, and protects your business inquiry information.",
    body: "Mack Knit Wear takes corporate privacy and commercial confidentiality seriously.\n\n1. Information We Collect: We collect information provided through business inquiry forms, including your full name, business email address, company name, country, and specific project requirements.\n\n2. Use of Information: Your data is utilized strictly to evaluate and respond to your inquiry, prepare commercial quotation proposals, and facilitate lawful business communications. We do not sell or lease your personal information to third parties.\n\n3. Data Storage & Security: Submissions are stored within an encrypted PostgreSQL database protected by strict row-level security and administrative authentication.\n\n4. Your Rights: You may request access to, correction of, or deletion of your commercial contact records at any time by contacting privacy@mackknitwear.com.",
  }),

  // Brands
  record(BRAND_1_ID, "brand", "norse-haven", {
    title: "Norse Haven",
    eyebrow: "ARCHITECTURAL KNITWEAR",
    category: "Contemporary Luxury",
    summary: "Subtle silhouettes in extra-fine merino wool and Mongolian cashmere, crafted for urban stillness.",
    body: "Norse Haven explores architectural proportion through heavy and fine knitwear. Born in 2022 as Mack Knit Wear's premier owned brand, it expresses minimalism with tactile warmth and uncompromising finishing.",
    relationship: "owned",
    featured: true,
    order: 1,
    image: "/images/knitwear.jpg",
    imageAlt: "Norse Haven autumn knitwear campaign",
    brandLogo: "/images/knitwear.jpg",
    brandLogoAlt: "Norse Haven Monogram",
    website: "https://norsehaven.example.com",
    store: "https://norsehaven.example.com/shop",
    craftsmanshipTitle: "Materials and Construction Philosophy",
    craftsmanshipSummary: "Every Norse Haven piece begins with single-origin fiber selection.",
    craftsmanshipBody: "We utilize 19.5-micron Australian merino and combed natural alpaca yarns. Linked by hand stitch-by-stitch to prevent seam puckering and ensure generational longevity.",
    craftsmanshipImage: "/images/knitwear.jpg",
    craftsmanshipImageAlt: "Hand linking inspection in Gazipur workshop",
    selectedProductIds: [PROD_1_ID, PROD_2_ID, PROD_3_ID],
    featuredCollectionId: COLLECTION_1_ID,
    gallery: [
      { id: "g-1", image: "/images/knitwear.jpg", alt: "Norse Haven studio detail", caption: "Natural undyed yarns in 7-gauge rib." },
      { id: "g-2", image: "/images/knitwear.jpg", alt: "Collar detail", caption: "Double-layered mock neck finishing." },
    ],
  }),

  // Collections
  record(COLLECTION_1_ID, "collection", "aw-2026-elements", {
    title: "Elements / AW 2026",
    eyebrow: "NORSE HAVEN COLLECTION",
    season: "Autumn / Winter 2026",
    summary: "Tactile knitwear informed by geological textures, moss gradients, and dense mountain wools.",
    body: "Elements showcases Norse Haven's most technically ambitious knit architectures to date, incorporating multi-directional ribbing, seamless saddle shoulders, and brushed bouclé textures.",
    image: "/images/knitwear.jpg",
    imageAlt: "Elements AW2026 lookbook campaign",
    brandId: BRAND_1_ID,
    productIds: [PROD_1_ID, PROD_2_ID, PROD_3_ID],
    featured: true,
    order: 1,
  }),

  // Products
  record(PROD_1_ID, "product", "fine-gauge-merino-crewneck", {
    title: "Fine-Gauge Merino Crewneck",
    eyebrow: "ESSENTIAL KNITWEAR",
    refCode: "MKW-MC-01",
    category: "Sweaters",
    brandId: BRAND_1_ID,
    summary: "Ultra-soft 14-gauge fully-fashioned crewneck sweater crafted from 100% Australian extrafine merino wool.",
    body: "Designed for seamless layering, this crewneck is knitted on computerized 14-gauge machinery with tubular neck ribbing, linked cuffs, and reinforced shoulder seams. Breathable, naturally temperature-regulating, and pre-washed for dimension stability.",
    image: "/images/knitwear.jpg",
    imageAlt: "Fine-gauge merino crewneck sweater in Oatmeal",
    materials: "100% Extrafine Australian Merino Wool (19.5 micron, Woolmark certified)",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Oatmeal Heather", "Deep Navy", "Charcoal Melange", "Black"],
    intendedUse: "Luxury daily wear, premium retail collections, private label programs.",
    customization: "Available for custom colorways, bespoke chest embroideries, and private label jacquard labels.",
    moq: "300 pieces per colorway",
    leadTime: "4 – 6 weeks from sample approval",
    featured: true,
    order: 1,
    specifications: [
      { label: "Gauge", value: "14-gauge flat knit" },
      { label: "Yarn Count", value: "2/30 Nm extrafine merino" },
      { label: "Weight", value: "260 GSM" },
      { label: "Construction", value: "Fully fashioned, linked seams" },
      { label: "Care", value: "Hand wash cold or eco dry clean" },
    ],
    gallery: [
      { id: "p1-g1", image: "/images/knitwear.jpg", alt: "Crewneck collar close up", caption: "Tubular collar ribbing" },
      { id: "p1-g2", image: "/images/knitwear.jpg", alt: "Ribbed cuff detail", caption: "Resilient 1x1 elasticated cuff" },
    ],
  }),

  record(PROD_2_ID, "product", "ribbed-cashmere-cardigan", {
    title: "Ribbed Cashmere Cardigan",
    eyebrow: "LUXURY OUTERWEAR",
    refCode: "MKW-CC-02",
    category: "Cardigans",
    brandId: BRAND_1_ID,
    summary: "Substantial 7-gauge cardigan with horn button placket, drop shoulders, and organic ribbing.",
    body: "A heavyweight cardigan combining Mongolian cashmere with superfine wool for exceptional loft without weight. Features genuine natural horn buttons, deep patch pockets, and reinforced placket tape.",
    image: "/images/knitwear.jpg",
    imageAlt: "Heavy ribbed cashmere cardigan in Sandstone",
    materials: "70% Superfine Lambswool, 30% Mongolian Cashmere",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Sandstone", "Olive Earth", "Midnight Navy"],
    intendedUse: "Refined outer-layering for autumn and winter.",
    customization: "Custom button choices (horn, corozo, or recycled metal) and bespoke wash finishes.",
    moq: "200 pieces per colorway",
    leadTime: "6 – 8 weeks from sample approval",
    featured: true,
    order: 2,
    specifications: [
      { label: "Gauge", value: "7-gauge fisherman rib" },
      { label: "Yarn Count", value: "2/16 Nm blended cashmere" },
      { label: "Weight", value: "540 GSM" },
      { label: "Buttons", value: "Natural matte horn, laser-engraved" },
    ],
    gallery: [
      { id: "p2-g1", image: "/images/knitwear.jpg", alt: "Horn button placket", caption: "Natural horn buttons" },
    ],
  }),

  record(PROD_3_ID, "product", "heavy-knit-fisherman-sweater", {
    title: "Heavy-Knit Fisherman Sweater",
    eyebrow: "HERITAGE RANGE",
    refCode: "MKW-FS-03",
    category: "Sweaters",
    brandId: BRAND_1_ID,
    summary: "Traditional cable and honeycomb cable sweater knitted from resilient 5-gauge British wool.",
    body: "Built for cold climates and rugged elegance, featuring five distinct heritage cable motifs across the chest and sleeves. Hand-finished collar and raglan sleeve construction provide unrestricted movement.",
    image: "/images/knitwear.jpg",
    imageAlt: "Heavy-knit fisherman sweater in Ecru",
    materials: "100% Pure British Wool (Undyed, water-repellent lanolin wash)",
    sizes: ["M", "L", "XL"],
    colors: ["Natural Ecru", "Moss Heather", "Storm Grey"],
    intendedUse: "Heritage outdoor lifestyle apparel.",
    customization: "Available with custom cable patterns and private label leather collar patches.",
    moq: "250 pieces per style",
    leadTime: "5 – 7 weeks",
    featured: false,
    order: 3,
    specifications: [
      { label: "Gauge", value: "5-gauge multi-cable knit" },
      { label: "Weight", value: "680 GSM" },
      { label: "Origin", value: "Manufactured in Gazipur, Bangladesh" },
    ],
  }),

  // Capabilities
  record("00000000-0000-4000-8000-000000000051", "capability", "computerized-flat-knitting", {
    title: "Computerized Multi-Gauge Flat Knitting",
    category: "Knitting Technology",
    summary: "State-of-the-art Japanese Shima Seiki machinery providing precision stitch architecture from 3G to 16G.",
    body: "Our knitting department hosts 60 high-speed computerized flat machines capable of complex jacquards, intarsia, multi-dimensional structures, and zero-waste whole-garment shaping. This enables designers to execute intricate textures while eliminating yarn cut-loss.",
    image: "/images/knitwear.jpg",
    imageAlt: "Computerized flat knitting machine in operation",
    processSteps: [
      { stepNumber: 1, title: "CAD Programming", description: "Designers translate knit structures into machine instructions using Apex 4 software." },
      { stepNumber: 2, title: "Tension & Swatch Calibration", description: "Yarn feeds and carriage speeds are tuned for exact micron shrinkage control." },
      { stepNumber: 3, title: "Automated Body Knitting", description: "Front, back, and sleeves are formed with integrated edge-holding selvages." },
      { stepNumber: 4, title: "Precision Hand Linking", description: "Collar, shoulders, and armholes are joined stitch-for-stitch on circular linking stands." },
    ],
    outputs: ["3G Chunky Knits", "14G Fine Merino Sweaters", "Complex Intarsia Motifs", "Tubular Jacquards"],
    order: 1,
    ctaLabel: "Inquire about production capacity",
    ctaHref: "/contact?type=Sourcing%20%26%20export",
  }),

  record("00000000-0000-4000-8000-000000000052", "capability", "sustainable-yarn-sourcing", {
    title: "Certified Sustainable Yarn Sourcing",
    category: "Raw Materials",
    summary: "Direct mill partnerships delivering GOTS organic cotton, RWS certified wool, and recycled cashmere.",
    body: "We partner directly with spinning mills in Italy, Portugal, and Bangladesh to source authenticated yarns with unbroken chain-of-custody documentation. Every batch is tested in our in-house lab for colorfastness, pilling resistance, and dimensional stability.",
    image: "/images/knitwear.jpg",
    imageAlt: "Yarn cone storage in temperature controlled room",
    processSteps: [
      { stepNumber: 1, title: "Fiber Verification", description: "Auditing certifications for Responsible Wool Standard (RWS) and GOTS organic cotton." },
      { stepNumber: 2, title: "Spectrophotometer Color Matching", description: "Digital lab dips ensure tight delta-E color accuracy before bulk winding." },
      { stepNumber: 3, title: "Conditioning & Waxing", description: "Yarn cones rest in 65% humidity rooms to optimize knitting glide and reduce friction breakage." },
    ],
    outputs: ["Australian Extrafine Merino", "Mongolian Cashmere", "Peruvian Pima Cotton", "Recycled Wool Blends"],
    order: 2,
    ctaLabel: "Request yarn sample cards",
    ctaHref: "/contact?type=Sample%20request",
  }),

  // Network
  record("00000000-0000-4000-8000-000000000061", "network", "alps-textile-group", {
    title: "Alps Textile Group",
    relationship: "partner",
    category: "European Spinning Partner",
    summary: "Northern Italian specialty spinners supplying carded cashmere and spun merino yarns.",
    body: "Our collaborative partnership with Alps Textile Group enables us to offer heritage European yarn stocks with fast turnaround for private-label collections.",
    image: "/images/knitwear.jpg",
    imageAlt: "Alps Textile Group logo",
    website: "https://alpstextiles.example.com",
    order: 1,
  }),

  record("00000000-0000-4000-8000-000000000062", "network", "koben-retail-partners", {
    title: "Køben Retail Partners",
    relationship: "client",
    category: "Scandinavian Department Stores",
    summary: "Stockist and wholesale distribution partner across Copenhagen, Oslo, and Stockholm.",
    body: "Mack Knit Wear has acted as a primary private-label manufacturer for Køben's signature knitwear lines since 2021.",
    image: "/images/knitwear.jpg",
    imageAlt: "Køben Retail Partners storefront",
    website: "https://kobenretail.example.com",
    order: 2,
  }),
];
